### ISSUE TITLE
Roadmap: Ability to generate code via xdrgen

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/exdr#3]
The primary objective here is to be able to use it to post stellar transactions. As part of that, we should eventually be able to take the .x files [here](https://github.com/stellar/js-stellar-base/tree/master/xdr) to generate code to use the stellar types.

**Comment by grossvogel** [comment]
https://github.com/stellar/xdrgen/pull/47

**Comment by grossvogel** [comment]
https://github.com/stellar/xdrgen/pull/47 is merged!
